//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _170516.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public string ImageType { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int UnitsInStock { get; set; }
        public double Discount { get; set; }
        public double UnitPrice { get; set; }
        public double DiscountedPrice { get; set; }
        public bool IsDiscountAvailable { get; set; }
        public bool IsAvailable { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> OrderCount { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> Rate { get; set; }
        public System.DateTime DateModified { get; set; }
        public string CreatedUserID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
    }
}
