//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _170516.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string RequestContent { get; set; }
        public bool IsNew { get; set; }
        public string ReplyUser { get; set; }
        public string Reply { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
